ecomrc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/create'

resources :products, only: [:index, :show]
  resources :products do 
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users

    get '/', to: 'pages#index' 
  end

  root 'products#index'

  get 'products/:id' => 'catalog#view'
  

end

ecomrc/app/models/product.rb
class Product < ActiveRecord::Base
	
	has_many :reviews, dependent: :destroy
	
	has_many :likes, as: :likable
	has_many :user_likes, through: :likes, source: :user
	
	belongs_to :user
	belongs_to :category

	mount_uploader  :photo, PhotoUploader
end

ecomrc/app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  #before_action require_admin
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params[:admin_product]
    end
end

ecomrc/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  @review = @product.reviews.build
  @last_reviews = @product.reviews.last(5)
  end



  # GET /products/new
  def new
    @product = Product.new
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :stock, :price, :photo)
    end
end

ecomrc/app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

ecomrc/app/helpers/products_helper.rb
module ProductsHelper
end

ecomrc/app/views/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :stock %><br>
  <%= f.number_field :stock %>
</div>
<div class="field">
  <%= f.label :price %><br>
  <%= f.number_field :price %>
</div>
<div class="field">
  <%= f.label :photo %><br>
  <%= f.file_field :photo %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

ecomrc/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

ecomrc/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Stock</th>
      <th>Price</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td><%= product.stock %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.photo %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

ecomrc/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

ecomrc/app/views/products/show.html.erb
<div class = "Product">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @product.photo %>
</p>


<%= link_to 'Back', products_path %>
</div>

<%= render partial: "reviews/review", collection: @last_reviews %>

<%= render "reviews/form" %>