ecomrc/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/create'

resources :products, only: [:index, :show]
  resources :products do 
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users

    get '/', to: 'pages#index' 
  end

  root 'products#index'

  get 'products/:id' => 'catalog#view'
  

end

ecomrc/app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable


  has_many :products, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :likes
  
  has_many :product_likes, through: :likes, source: :likeable,
  source_type: 'Product'
  has_many :review_likes, through: :likes, source: :likeable,
  source_type: 'Review'
  
  enum role: [:guest, :moderator]
  validates :name, :lastname, :username, presence:true 
  
  
end

ecomrc/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  #before_action require_admin
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params[:admin_user]
    end
end

ecomrc/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ecomrc/app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ecomrc/app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

ecomrc/app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

ecomrc/app/views/admin/users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

ecomrc/app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>